org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

org.gradle.java.home=C\:\\Users\\nasee\\AppData\\Local\\Programs\\Eclipse Adoptium\\jdk-17.0.17.10-hotspot
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
org.gradle.caching=true
kotlin.incremental=false

kotlin.incremental=false
systemProp.flutter.storageBaseUrl=https://storage.flutter-io.cn
